# version del formato de docker-compose.yml
# Este archivo define los servicios necesarios para la aplicación
version: "3.8"

services:
  frontend:
    build:
      # Donde va a buscar el Dockerfile (la carpeta)
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    environment:
      # Variables de entorno para la aplicación frontend
      - VITE_API_URL=http://localhost:5000
    # Comando para iniciar el servidor de desarrollo
    # --host permite que el servidor sea accesible desde otras máquinas en la red
    # Esto es útil para el desarrollo en contenedores
    # Si no se especifica, el servidor solo será accesible desde localhost
    command: npm run dev -- --host

  api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
      # Indica que depende de postgres y modifica el orden de arranque
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proyecto-final-db
    volumes:
      # Monta un volumen para persistir los datos de la base de datos
      - pgdata:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
